name: Source Composition Analysis Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  security-sca:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master2
      - uses: snyk/actions/node@master2
      - name: Run Snyk to check for vulnerabilities
        run: snyk test --all-projects --fail-on=all
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
     
